### ISSUE TITLE
This is just exact copy of another repo

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mpolinowski/floating-menu-button-react-component#1]
What's your purpose on copying same code from original one with just diffrent README.md?
https://github.com/ifndefdeadmau5/react-floating-button-menu

**Comment by mpolinowski** [comment]
I originally wanted to start adding things to it - but the project ended up using Material-UI, that already comes with a floating button component:

https://github.com/mpolinowski/mui-gatsby-markdown/blob/master/src/components/Layout/floating-buttons.jsx

I might come back to this in the future. But there is no development at the moment.

**Comment by mpolinowski** [comment]
You are absolutely right about the link back to the origin - it is missing because this repository never went anywhere.

For this I apologize - it is not open source etiquette.

But so is cursing in Github comments, which is clearly unnecessary.

The next time I might need this, I will do a proper fork.


kind regards


Mike
